### ISSUE TITLE
FileNotfound error 

### ISSUE THREAD

**Issue by Mr-Lazzy** [waffl3ss/NameSpi#1]
Traceback (most recent call last):
  File "/opt/OSINT/NameSpi/./NameSpi.py", line 453, in <module>
    main_generator()
  File "/opt/OSINT/NameSpi/./NameSpi.py", line 450, in main_generator
    mangler(mangleMode, outputfile)
  File "/opt/OSINT/NameSpi/./NameSpi.py", line 378, in mangler
    fileInput = open(inputFileName, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/home/kali/Downloads/result'

Getting this error even after creating output file name

**Comment by waffl3ss** [comment]
I'm working on a new version that reworks the way the output file is handled. Should be coming in the next few days.

**Comment by waffl3ss** [comment]
New version just got updated. If you still have issues let me know. Thank you!
